repository:
  topics: metrics, prometheus, prometheus-client
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: true
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: false
  enable_vulnerability_alerts: true

teams:
  - name: devs
    permission: maintain

branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts: ["🏭 Build & Test"]
      enforce_admins: false
      required_linear_history: false
      restrictions: null
